//----------------------------------------------------------------------
//	Copyright (C) 2020-present Matias N. Goldberg ("dark_sylinc")
//  Under MIT License
//  This file is part of Yangen.
//----------------------------------------------------------------------

#pragma once

/**
@file
Subclass of wxAnimationPanel, which is generated by wxFormBuilder.
*/

#include "OgrePrerequisites.h"

#include <OgreColourValue.h>
#include "wxOgreMeshViewerMainFrame.h"

namespace Ogre
{
	class MovableText;
}

/** Implementing wxAnimationPanel */
class AnimationPanel : public wxAnimationPanel
{
protected:
	// Handlers for wxAnimationPanel events.
	void OnChangedAnimationName( wxCommandEvent &event );
	void OnAnimationChangeTime( wxCommandEvent &event );
	void OnAnimationChangeTimeScroll( wxScrollEvent &event );
	void OnButtonPlaybackSkelAnim( wxCommandEvent &event );
	void OnAnimationRateChange( wxCommandEvent &event );
	void OnLoopAnimation( wxCommandEvent &event );
	void OnRadioInterpolationMode( wxCommandEvent &event );
	void OnBoneSizeChange( wxScrollEvent &event );
	void OnNodeTrackSelect( wxTreeEvent &event );

public:
	/** Constructor */
	AnimationPanel( wxWindow *parent, Ogre::SceneManager *sceneManager );
};
