//----------------------------------------------------------------------
//	Copyright (C) 2020-present Matias N. Goldberg ("dark_sylinc")
//  Under MIT License
//  This file is part of Yangen.
//----------------------------------------------------------------------

#pragma once

/**
@file
Subclass of Visualization, which is generated by wxFormBuilder.
*/

#include "../../src/Autogenerated/wxYangen.h"

//// end generated include

class YangenWindowImpl;

/** Implementing Visualization */
class VisualizationPanelImpl : public VisualizationPanel
{
	YangenWindowImpl *m_yangenWindowImpl;

public:
	/** Constructor */
	VisualizationPanelImpl( YangenWindowImpl *yangenWindowImpl );
	//// end generated class members

	virtual void OnChoice( wxCommandEvent& event );
};
